name: Deploy Node App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u${{secrets.DOCKER_USERNAME}} -p${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t zxc22164017/nodejs-app .
      - name: Publish Image to Docker hub
        run: docker push zxc22164017/nodejs-app:latest

  delpoy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker pull zxc22164017/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name nodejs-app-container --env MONGODB_URL='${{secrets.MONGODB_URL}}' --env SECRET='${{secrets.SECRET}}' --env ACCESS_KEY_ID='${{secrets.ACCESS_KEY_ID}}' --env SECRET_ACCESS_KEY='${{secrets.SECRET_ACCESS_KEY}}' --env S3_BUCKET='${{secrets.S3_BUCKET}}' --REDIS_PASSWORD='${{secrets.REDIS_PASSWORD}}' zxc22164017/nodejs-app
