name: Deploy Node App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u${{secrets.DOCKER_USERNAME}} -p${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t zxc22164017/nodejs-app .
      - name: Publish Image to Docker hub
        run: docker push zxc22164017/nodejs-app:latest

  delpoy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker pull zxc22164017/nodejs-app:latest
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name nodejs-app-container  zxc22164017/nodejs-app
        env:
          MONGO_URL: "${{secrets.MONGODB_URL}}"
          SECRET: "${{secrets.SECRET}}"
          ACCESS_KEY_ID: ${{secrets.ACCESS_KEY_ID}}
          SECRET_ACCESS_KEY: "${{secrets.SECRET_ACCESS_KEY}}"
          S3_BUCKET: ${{secrets.S3_BUCKET}}
